permalink: /:year/:month/:day/:title.html
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
markdown: kramdown
kramdown:
  input: GFM  

# 作者信息
author: 
  name: Ethan Cao
  email: god13dog@163.com
  link: http://taominer.github.com
  weibo: http://weibo.com/1752135657
  github: http://github.com/TaoMiner
  # linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 曹艺馨的博客
description: My personal blog
url: http://taominer.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/ethan_avatar.jpg
favicon: /public/img/ethan_avatar.jpg

# google analytics 设置
ga:
  id: UA-70766178-1
  url: taominer.github.io

# disqus 设置
disqus:
  shortname: ethancao

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档