permalink: /:year/:month/:day/:title.html
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
markdown: kramdown
kramdown:
  input: GFM  

# 作者信息
author: 
  name: Ethan Cao
  email: god13dog@163.com
  link: http://taominer.github.com
  weibo: http://weibo.com/1752135657
  github: http://github.com/TaoMiner
  # linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: Ethan's Blog
description: 机器学习爱好者
url: http://taominer.github.io
rss_url: /pages/feed.xml
keyword: "机器学习"

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，我想去看看。"
sidebar-avatar: /public/img/ethan_avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# google analytics 设置
ga:
  id: UA-70766178-1
  url: taominer.github.io

# disqus 设置
# disqus_username: ethancao
# Duoshuo settings
duoshuo_username: ethancao
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing
